---
title: "PSTAT 174 - Final Project"
author: "McLane Brown, Diane Phann, Dennis Wang, Davis Messer"
date: "Spring 2018"
output:
  pdf_document:
    toc: yes
  html_document:
    number_sections: yes
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE,fig.align = "center")
```

## Notes/Useful Code

*

```{r eval=F}
dates <- t(sapply(emissiondata$YYYYMM, function(x) substring(x, first=c(1,5), last=c(4, 6))))
dat <- cbind(emissiondata, dates)

names(dat)[names(dat) == "1"] <- "Year"
names(dat)[names(dat) == "2"] <- "Month"

str(dat)



sarima(y12, 3, 2, 1, 1, 1, 0, 12)

hist(residuals(fit)) # close to normal
```

## Packages

```{r packages}
# library(dplyr)
# library(plyr)
library(MASS)
library(qpcR)
library(astsa)
```

## Data

```{r data}
emissiondata<-read.csv("MER_T12_06.csv",header=TRUE, stringsAsFactors = FALSE)
emissiondata = emissiondata[1:5]
str(emissiondata)

TXEIEUS<-read.csv("TXEIEUS.csv",header=TRUE)

Total_Energy_Electric_Power <- ts(TXEIEUS[,3],start=c(1996,1),frequency=12) #Time series data
```

## Plotting Original Data

```{r plot}
par(mfrow=c(1,1))
plot(Total_Energy_Electric_Power,main="Total Energy Electric Power CO2 Emission per Million Metric Ton") #Plotting time series

#Nonconstant variance
par(mfrow = c(1,2))
acf(Total_Energy_Electric_Power,lag.max = 60,main = "")
#Clearly cyclicial trends
pacf(Total_Energy_Electric_Power,lag.max = 60,main = "")
title("Original Time Series", line = -1, outer=TRUE)
var(Total_Energy_Electric_Power) #Very big variance
max(Total_Energy_Electric_Power)
min(Total_Energy_Electric_Power)
```

## Deciding on a Transformation

```{r detrend}
par(mfrow=c(1,1))
t = 1:length(Total_Energy_Electric_Power)
fit = lm(Total_Energy_Electric_Power ~ t)
bcTransform = boxcox(Total_Energy_Electric_Power ~ t,plotit = TRUE) #package qpcR
#Lab03 since the CI includes 0, then BC transformation is lamda or log(data)

Total_Energy_Electric_Power.log <- log(Total_Energy_Electric_Power)
op <- par(mfrow = c(1,2))
ts.plot(Total_Energy_Electric_Power,main = "Original data",ylab = expression(X[t]))
ts.plot(Total_Energy_Electric_Power.log,main = "Box-Cox tranformed data-log", ylab = expression(Y[t]))
```


## Post Transformation

```{r}
par(mfrow=c(1,2))
acf(Total_Energy_Electric_Power.log,lag.max = 60,main = "")
pacf(Total_Energy_Electric_Power.log,lag.max = 60,main = "")
title("Box-Cox Transformed Time Series", line = -1, outer=TRUE)
#It looks like significant correlation at every 12 lag and we can conclude seasonal component d=12
#Comparing variance between the original and transformed
var(Total_Energy_Electric_Power)
var(Total_Energy_Electric_Power.log) #Way much lower - log trans
```

## De-trending

```{r}
par(mfrow=c(1,1))
y1 = diff(Total_Energy_Electric_Power.log, 2)

plot(y1,main = "De-trended Time Series at lag 2",ylab = expression(nabla~Y[t])) #quadratic trend
abline(h = 0,lty = 2)
acf(y1, main="")
pacf(y1, main="")
var(y1) #lower than B.C. no transformation

#Differencing more than once actually increase the variance, indicating over differencing 
#Differencing more than once at lag of 1 increased variance
#Differencinng more than once at lag of 2 actually lowered variance

```

## Removing Seasonal Component

```{r}
# Diference at lag = 12 (cycle determined by the ACF) to remove seasonal component
y12 = diff(y1, 12)
ts.plot(y12,main = "De-trended/seasonalized Time Series of 12",ylab = expression(nabla^{12}~nabla~Y[t]))
abline(h = 0,lty = 2)
var(y12)

# Re-calculate the sample variance and examine the ACF and PACF for first difference
op = par(mfrow = c(1,2))
acf(y1,lag.max = 60,main = "")
pacf(y1,lag.max = 60,main = "") #P is possibly 1
title("De-trended Time Series", line = -1, outer=TRUE)
```

```{r}
op = par(mfrow = c(1,2))
acf(y12,lag.max = 60,main = "")
pacf(y12,lag.max = 60,main = "")
title("De-trended/seasonalized Time Series",line = -1, outer=TRUE)
#Possibly MA(1) from ACf as the rest are in 95 CI but PACF does not look like it
ar(Total_Energy_Electric_Power, method="yule-walker")
ar(Total_Energy_Electric_Power, aic = TRUE, order.max = NULL, method = c("ols")) #using OLS method
ar(Total_Energy_Electric_Power, aic = TRUE, order.max = NULL, method = c("mle")) #using MLE method
#All three methods suggest order of 12, so AR(12)
```

## Difference at Lag 1 (for another model possibility)

```{r}
y2 = diff(Total_Energy_Electric_Power.bc, 1)
plot(y1,main = "De-trended Time Series at lag 1",ylab = expression(nabla~Y[t])) #quadratic trend
abline(h = 0,lty = 2)
# acf(y1, main="")
# pacf(y1, main="")

# Diference at lag = 12 (cycle determined by the ACF) to remove seasonal component
y2.12 = diff(y1, 12)
ts.plot(y2.12,main = "De-trended/seasonalized Time Series of 12",ylab = expression(nabla^{12}~nabla~Y[t]))
abline(h = 0,lty = 2)

op = par(mfrow = c(1,2))
acf(y2,lag.max = 60,main = "")
pacf(y2,lag.max = 60,main = "") #P is possibly 1
title("De-trended Time Series", line = -1, outer=TRUE)

op = par(mfrow = c(1,2))
acf(y2.12,lag.max = 60,main = "")
pacf(y2.12,lag.max = 60,main = "")
title("De-trended/seasonalized Time Series", line = -1, outer=TRUE)
```

## Three Possible Models

$SARIMA(p,d,q)\times(P,D,Q)_s$

1. $SARIMA(3, 2, 1)\times(1, 1, 0)_{12}$

2. $SARIMA(2,2,1)\times(2,1,0)_{12}$

3. $SARIMA(3, 1, 1)\times(1, 1, 0)_{12}$

## Model Selection

```{r trash}
ar(Total_Energy_Electric_Power.bc, method="yule-walker") #AR(12)
source("innovations.r")
acvf = acf(Total_Energy_Electric_Power.bc, plot=FALSE, lag.max = length(Total_Energy_Electric_Power.bc))$acf[,1,1] * var(Total_Energy_Electric_Power.bc)

mod1.fit = sarima(y12, 3, 2, 1, 1, 1, 0, 12)
mod1.fit
# -4.03956, -4.028437, -4.948749
mod2.fit = sarima(y12, 2, 2, 1, 2, 1, 0, 12)
mod3.fit = sarima(y12, 3, 1, 1, 1, 1, 0, 12)

mod4.fit = sarima(y12, 0, 2, 1, 0, 1, 1, 12)
mod4.fit
# -4.039613, -4.029962

mod5.fit = sarima(y12, 0, 1, 1, 0, 1, 1, 12)
mod5.fit
# -4.531358, -4.52203, -5.501088

mod1.fit$AICc
mod2.fit$AICc
mod3.fit$AICc
Box.test(residuals(mod1.fit), type = "Ljung")

```



```{r Ljung}
fit1 <- arima(x = y12, order = c(3,2,1), seasonal = list(order = c(1, 1, 0), period = 12))
Box.test(residuals(fit1), type = "Ljung")
# .5166

fit2 <- arima(x = y12, order = c(2,2,1), seasonal = list(order = c(2, 1, 0), period = 12))
Box.test(residuals(fit2), type = "Ljung")
# .4557

fit3 <- arima(x = y12, order = c(3,1,1), seasonal = list(order = c(1, 1, 0), period = 12))
Box.test(residuals(fit3), type = "Ljung")
# .5764

```

Models 2 and 3 have the lowest AICc and AIC

```{r}
mod1.fit
```










